
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "hoaint",
    "password": "123456",
    "hovaten": "Nguyễn Thị Hoài"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "namnth",
    "password": "1234567"
}


###
POST http://localhost:5000/danhmuc/hocvi
Content-Type: application/json
{
    "mahocvi": "5",
    "ten": "Thạc sĩ 5"                                                                                                                                                                                                                                                                                                                                                                                                                        
}

###
POST http://localhost:5000/danhmuc/chucvu
Content-Type: application/json
{
    "machucvu": "PTP",
    "ten": "Phó Trưởng Phòng"                                                                                                                                                                                                                                                                                                                                                                                                                        
}

###
POST http://localhost:5000/detai/dotdangky
Content-Type: application/json


{
    "madot": "DTSV2023",
    "tendot": "Đợt đăng ký đề tài sinh viên năm 2023",
    "nam": "2023",
    "ghichu": "note",
    "trangthai": "Mở đăng ký"

}

###
POST http://localhost:5000/thongbao/thongbaochung
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWM4NWNjNDMxMjFhNTMxMmE5OTI1YSIsImlhdCI6MTY1NTQ4MjQ4OSwiZXhwIjoxNjU1NDgzMTQ5fQ.--psQNlSZA2WAGyCGZHMj4DF4t09wcdFgaY1u4xy6mE
{
    "tieude": "Thông báo tạo",
    "noidung": "Thông báo đăng ký.....",
    "nguoithongbao": "Nguyễn Thị Hoaì 2"
}

###
POST http://localhost:5000/danhmuc/khoa
Content-Type: application/json
{
    "makhoa": "CNTT",
    "ten": "Khoa CNTT"                                                                                                                                                                                                                                                                                                                                                                                                                        
}