export const apiUrl = 'http://localhost:5000'

export const LOCAL_STORAGE_TOKEN_NAME = 'quanly-nckh'

//Thông báo chung
export const TB_LOADED_SUCCESS = 'TB_LOADED_SUCCESS'
export const TB_LOADED_FAIL = 'TB_LOADED_FAIL'
export const TB_ADD = 'TB_ADD'
export const DELETE_TB = 'DELETE_TB'
export const UPDATE_TB = 'UPDATE_TB'
export const FIND_TB = 'FIND_TB'

//Đợt đăng ký đề tài
export const DOTDANGKY_LOADED_SUCCESS = 'DOTDANGKY_LOADED_SUCCESS'
export const DOTDANGKY_LOADED_FAIL = 'DOTDANGKY_LOADED_FAIL'
export const DOTDANGKY_ADD = 'DOTDANGKY_ADD'
export const DELETE_DOTDANGKY = 'DELETE_DOTDANGKY'
export const UPDATE_DOTDANGKY = 'UPDATE_DOTDANGKY'
export const FIND_DOTDANGKY = 'FIND_DOTDANGKY'

//Đăng ký đề tài sinh viên
export const DETAISV_LOADED_SUCCESS = 'DETAISV_LOADED_SUCCESS'
export const DETAISV_LOADED_FAIL = 'DETAISV_LOADED_FAIL'
export const DETAISV_ADD = 'DETAISV_ADD'
export const DELETE_DETAISV = 'DELETE_DETAISV'
export const UPDATE_DETAISV = 'UPDATE_DETAISV'
export const FIND_DETAISV = 'FIND_DETAISV'

//Danh mục/ Cấp đề tài
export const CAPDETAI_LOADED_SUCCESS = 'CAPDETAI_LOADED_SUCCESS'
export const CAPDETAI_LOADED_FAIL = 'CAPDETAI_LOADED_FAIL'
export const CAPDETAI_ADD = 'CAPDETAI_ADD'
export const DELETE_CAPDETAI = 'DELETE_CAPDETAI'
export const UPDATE_CAPDETAI = 'UPDATE_CAPDETAI'
export const FIND_CAPDETAI = 'FIND_CAPDETAI'

//Danh mục/Vai trò hội đồng
export const VAITROHĐ_LOADED_SUCCESS = 'VAITROHĐ_LOADED_SUCCESS'
export const VAITROHĐ_LOADED_FAIL = 'VAITROHĐ_LOADED_FAIL'
export const VAITROHĐ_ADD = 'VAITROHĐ_ADD'
export const DELETE_VAITROHĐ = 'DELETE_VAITROHĐ'
export const UPDATE_VAITROHĐ = 'UPDATE_VAITROHĐ'
export const FIND_VAITROHĐ= 'FIND_VAITROHĐ'



//Danh mục trong database
export const KHOAXETDUYET_LOADED_SUCCESS = 'KHOAXETDUYET_LOADED_SUCCESS'
export const KHOAXETDUYET_LOADED_FAIL = 'KHOAXETDUYET_LOADED_FAIL'
export const KHOAXETDUYET_ADD = 'KHOAXETDUYET_ADD'
export const DELETE_KHOAXETDUYET = 'DELETE_KHOAXETDUYET'
export const UPDATE_KHOAXETDUYET = 'UPDATE_KHOAXETDUYET'
export const FIND_KHOAXETDUYET = 'FIND_KHOAXETDUYET'