export const apiUrl = 'http://localhost:5000'

export const LOCAL_STORAGE_TOKEN_NAME = 'quanly-nckh'

//Thông báo chung
export const TB_LOADED_SUCCESS = 'TB_LOADED_SUCCESS'
export const TB_LOADED_FAIL = 'TB_LOADED_FAIL'
export const TB_ADD = 'TB_ADD'
export const DELETE_TB = 'DELETE_TB'
export const UPDATE_TB = 'UPDATE_TB'
export const FIND_TB = 'FIND_TB'

//Đợt đăng ký đề tài
export const DOTDANGKY_LOADED_SUCCESS = 'DOTDANGKY_LOADED_SUCCESS'
export const DOTDANGKY_LOADED_FAIL = 'DOTDANGKY_LOADED_FAIL'
export const DOTDANGKY_ADD = 'DOTDANGKY_ADD'
export const DELETE_DOTDANGKY = 'DELETE_DOTDANGKY'
export const UPDATE_DOTDANGKY = 'UPDATE_DOTDANGKY'
export const FIND_DOTDANGKY = 'FIND_DOTDANGKY'

//Đăng ký đề tài cán bộ
export const DETAICB_LOADED_SUCCESS = 'DETAICB_LOADED_SUCCESS'
export const DETAICB_LOADED_FAIL = 'DETAICB_LOADED_FAIL'
export const DETAICB_ADD = 'DETAICB_ADD'
export const DELETE_DETAICB = 'DELETE_DETAICB'
export const UPDATE_DETAICB = 'UPDATE_DETAICB'
export const FIND_DETAICB = 'FIND_DETAICB'

//Đăng ký đề tài sinh viên
export const DETAISV_LOADED_SUCCESS = 'DETAISV_LOADED_SUCCESS'
export const DETAISV_LOADED_FAIL = 'DETAISV_LOADED_FAIL'
export const DETAISV_ADD = 'DETAISV_ADD'
export const DELETE_DETAISV = 'DELETE_DETAISV'
export const UPDATE_DETAISV = 'UPDATE_DETAISV'
export const FIND_DETAISV = 'FIND_DETAISV'

//Đợt kiểm tra tiến độ
export const DOTKIEMTRATĐ_LOADED_SUCCESS = 'DOTKIEMTRATĐ_LOADED_SUCCESS'
export const DOTKIEMTRATĐ_LOADED_FAIL = 'DOTKIEMTRATĐ_LOADED_FAIL'
export const DOTKIEMTRATĐ_ADD = 'DOTKIEMTRATĐ_ADD'
export const DELETE_DOTKIEMTRATĐ = 'DELETE_DOTKIEMTRATĐ'
export const UPDATE_DOTKIEMTRATĐ = 'UPDATE_DOTKIEMTRATĐ'
export const FIND_DOTKIEMTRATĐ = 'FIND_DOTKIEMTRATĐ'

//Quản lý hội đồng
export const HOIDONG_LOADED_SUCCESS = 'HOIDONG_LOADED_SUCCESS'
export const HOIDONG_LOADED_FAIL = 'HOIDONG_LOADED_FAIL'
export const HOIDONG_ADD = 'HOIDONG_ADD'
export const DELETE_HOIDONG = 'DELETE_HOIDONG'
export const UPDATE_HOIDONG = 'UPDATE_HOIDONG'
export const FIND_HOIDONG = 'FIND_HOIDONG'

//Danh mục/ Cấp đề tài
export const CAPDETAI_LOADED_SUCCESS = 'CAPDETAI_LOADED_SUCCESS'
export const CAPDETAI_LOADED_FAIL = 'CAPDETAI_LOADED_FAIL'
export const CAPDETAI_ADD = 'CAPDETAI_ADD'
export const DELETE_CAPDETAI = 'DELETE_CAPDETAI'
export const UPDATE_CAPDETAI = 'UPDATE_CAPDETAI'
export const FIND_CAPDETAI = 'FIND_CAPDETAI'

//Danh mục/Vai trò hội đồng
export const VAITROHĐ_LOADED_SUCCESS = 'VAITROHĐ_LOADED_SUCCESS'
export const VAITROHĐ_LOADED_FAIL = 'VAITROHĐ_LOADED_FAIL'

//Danh mục/Vai trò tham gia
export const VAITROTG_LOADED_SUCCESS = 'VAITROTG_LOADED_SUCCESS'
export const VAITROTG_LOADED_FAIL = 'VAITROTG_LOADED_FAIL'
export const VAITROTG_ADD = 'VAITROTG_ADD'
export const DELETE_VAITROTG = 'DELETE_VAITROTG'
export const UPDATE_VAITROTG = 'UPDATE_VAITROTG'
export const FIND_VAITROTG = 'FIND_VAITROTG'

//Danh mục/ lĩnh vực
export const LINHVUC_LOADED_SUCCESS = 'LINHVUC_LOADED_SUCCESS'
export const LINHVUC_LOADED_FAIL = 'LINHVUC_LOADED_FAIL'
export const LINHVUC_ADD = 'LINHVUC_ADD'
export const DELETE_LINHVUC = 'DELETE_LINHVUC'
export const UPDATE_LINHVUC = 'UPDATE_LINHVUC'
export const FIND_LINHVUC = 'FIND_LINHVUC'


//Danh mục khoa
export const KHOA_LOADED_SUCCESS = 'KHOA_LOADED_SUCCESS'
export const KHOA_LOADED_FAIL = 'KHOA_LOADED_FAIL'

//Danh loại hội đồng
export const LOAIHĐ_LOADED_SUCCESS = 'LOAIHĐ_LOADED_SUCCESS'
export const LOAIHĐ_LOADED_FAIL = 'LOAIHĐ_LOADED_FAIL'

//Danh mục chức vụ
export const CHUCVU_LOADED_SUCCESS = 'CHUCVU_LOADED_SUCCESS'
export const CHUCVU_LOADED_FAIL = 'CHUCVU_LOADED_FAIL'


//Quản trị/ quản lý người dùng
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'
export const USER_ADD = 'USER_ADD'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const FIND_USER = 'FIND_USER'